language: cpp

sudo: required
dist: trusty

matrix:
  allow_failures:
    - compiler: clang
  fast_finish: true
  include:
    - compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-4.9
            - libconfig++-dev
            - valgrind
      env: CXX_COMPILER=g++-4.9 C_COMPILER=gcc-4.9 BUILD_TYPE=Release
    - compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-4.9
            - libconfig++-dev
            - valgrind
      env: CXX_COMPILER=g++-4.9 C_COMPILER=gcc-4.9 BUILD_TYPE=Debug
    - compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-5
            - libconfig++-dev
            - valgrind
      env: CXX_COMPILER=g++-5 C_COMPILER=gcc-5 BUILD_TYPE=Release
    - compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-5
            - libconfig++-dev
            - valgrind
      env: CXX_COMPILER=g++-5 C_COMPILER=gcc-5 BUILD_TYPE=Debug
    - compiler: clang
      before_script:
        - curl http://llvm.org/apt/llvm-snapshot.gpg.key | sudo apt-key add -
        - echo "deb http://llvm.org/apt/trusty/ llvm-toolchain-trusty-3.8 main" | sudo tee -a /etc/apt/sources.list
        - sudo apt-get update -qq
        - sudo apt-get install clang-3.8 -y
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - libconfig++-dev
            - valgrind
      env: CXX_COMPILER=clang++-3.8 C_COMPILER=clang-3.8 BUILD_TYPE=Release
    - compiler: clang
      before_script:
        - curl http://llvm.org/apt/llvm-snapshot.gpg.key | sudo apt-key add -
        - echo "deb http://llvm.org/apt/trusty/ llvm-toolchain-trusty-3.8 main" | sudo tee -a /etc/apt/sources.list
        - sudo apt-get update -qq
        - sudo apt-get install clang-3.8 -y
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - libconfig++-dev
            - valgrind
      env: CXX_COMPILER=clang++-3.8 C_COMPILER=clang-3.8 BUILD_TYPE=Debug

branches:
  only:
    - master

script:
  - mkdir build && cd build
  - cmake -DCMAKE_CXX_COMPILER=$CXX_COMPILER -DCMAKE_C_COMPILER=$C_COMPILER -DCMAKE_BUILD_TYPE=$BUILD_TYPE ..
  - make
  - ctest --output-on-failure -D ExperimentalMemCheck
  - valgrind --leak-check=full --error-exitcode=1 ./goiovalues
